# Generated by Django 3.1.1 on 2020-09-19 00:08

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20200919_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdate',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bookingtime',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2020, 9, 19, 1, 8, 12, 782777)),
        ),
    ]
