# Generated by Django 3.1.1 on 2020-09-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20200919_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingtime',
            name='duration',
        ),
        migrations.AlterField(
            model_name='bookingtime',
            name='end_time',
            field=models.PositiveSmallIntegerField(choices=[('08', '8'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '01'), ('14', '02'), ('15', '03'), ('16', '04'), ('17', '05'), ('18', '06')], default='18'),
        ),
        migrations.AlterField(
            model_name='bookingtime',
            name='start_time',
            field=models.PositiveSmallIntegerField(choices=[('08', '8'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '01'), ('14', '02'), ('15', '03'), ('16', '04'), ('17', '05')], default='08'),
        ),
    ]
