# Generated by Django 3.1.1 on 2020-09-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_auto_20200921_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtime',
            name='end_time',
            field=models.CharField(choices=[('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18')], default='18', max_length=2),
        ),
        migrations.AlterField(
            model_name='bookingtime',
            name='start_time',
            field=models.CharField(choices=[('08', '08')], default='08', max_length=2),
        ),
    ]
