# Generated by Django 3.1.1 on 2020-09-22 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0008_auto_20200921_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingtime',
            old_name='end_time',
            new_name='end_hour',
        ),
        migrations.RenameField(
            model_name='bookingtime',
            old_name='start_time',
            new_name='start_hour',
        ),
        migrations.AddField(
            model_name='bookingdate',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingtime',
            name='end_minute',
            field=models.CharField(choices=[('00', '00'), ('15', '15'), ('30', '30'), ('45', '45')], default='00', max_length=2),
        ),
        migrations.AddField(
            model_name='bookingtime',
            name='start_minute',
            field=models.CharField(choices=[('00', '00'), ('15', '15'), ('30', '30'), ('45', '45')], default='00', max_length=2),
        ),
    ]
